apiVersion: v1
kind: ReplicationController
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    app: controller
  template:
    metadata:
      name: controller
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: overrider/capstonetest
        ports:
        - containerPort: 80
